# Generated by Django 5.2 on 2025-05-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Gastroenterology', 'Gastroenterology'), ('General Medicine', 'General Medicine'), ('Gynaecology', 'Gynaecology'), ('Hematology', 'Hematology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Physiotherapy', 'Physiotherapy'), ('Plastic Surgery', 'Plastic Surgery'), ('Radiology', 'Radiology'), ('Urology', 'Urology'), ('Dental', 'Dental')], max_length=100),
        ),
    ]
